In [3]:
import pandas as pd
import numpy as np

In [4]:
# PREPROCESAMIENTO BASICO
# 1. Como tratar los nulls.
# 2. Como transformar las variables categóricas o strings
# 3. Es necesario transformar la distribución de algunas variables?.
# 4. como gestiono los outliers.
# 5. Necesito estandarizar los valores.

In [5]:
# 1. NULLs:
# 1.1 No hacer nada. (para HistGradientBoost, XGBoost, LightGBM)
# 1.2 Eliminar filas o columnas con Null. (cuando hay muy pocas filas o muchas columnas)
# 1.3 Imputación, basada en más frecuente, media, mediana, k-nn.
# 1.4 Es darle un valor diferente al resto de datos. Si es catégorico : NO disponible, si
# numérico valor alejado.

df_train = pd.read_csv("data/preprocessed/train_data.csv")

In [6]:
df_train = df_train.replace({9:np.nan})

In [7]:
df_train.isna().sum()

Price                      0
city                       0
Area                       0
Location                   0
No. of Bedrooms            0
Resale                     0
MaintenanceStaff       14164
Gymnasium              14164
SwimmingPool           14164
LandscapedGardens      14164
JoggingTrack           14164
RainWaterHarvesting    14164
IndoorGames            14164
ShoppingMall           14164
Intercom               14164
SportsFacility         14164
ATM                    14164
ClubHouse              14164
School                 14164
24X7Security           14164
PowerBackup            14164
CarParking             14164
StaffQuarter           14164
Cafeteria              14164
MultipurposeRoom       14164
Hospital               14164
WashingMachine         14164
Gasconnection          14164
AC                     14164
Wifi                   14164
Children'splayarea     14164
LiftAvailable          14164
BED                    14164
VaastuCompliant        14164
Microwave              14164
GolfCourse             14164
TV                     14164
DiningTable            14164
Sofa                   14164
Wardrobe               14164
Stadium                14164
dtype: int64

In [24]:
df_w_bool = df_train.copy()
df_w_bool[df_w_bool.columns[5:]] = df_w_bool[df_w_bool.columns[5:]].replace({0:'NO', 1:'SI', np.nan:'NO_DISPONIBLE'})

In [25]:
df_w_bool

,Price,city,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,11000000,Delhi,1400,Sector 11 Dwarka,2,SI,NO,NO,NO,NO,...,SI,SI,NO,SI,NO,SI,SI,SI,NO,SI
1,4883000,Bangalore,1565,Varthur,3,NO,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE
2,2730000,Delhi,1000,Noida,3,SI,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE
3,11100000,Mumbai,655,Andheri East,2,SI,SI,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,5000000,Chennai,1225,Maraimalai Nagar,3,NO,NO,SI,SI,NO,...,SI,NO,NO,NO,NO,NO,NO,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20969,75000000,Delhi,1700,Road Number 1,2,SI,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE
20970,6900000,Bangalore,3400,Ulsoor,4,SI,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE
20971,6859999,Bangalore,1332,Banashankari,3,NO,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE
20972,3500000,Delhi,675,Bindapur,3,SI,NO,NO,NO,NO,...,SI,NO,NO,NO,NO,NO,NO,NO,NO,NO
20973,27500000,Delhi,811,Delhi,2,SI,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,...,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE,NO_DISPONIBLE

In [26]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
df_w_bool['No. of Bedrooms'] = imputer.fit_transform(df_w_bool[['No. of Bedrooms']])

In [27]:
df_w_bool.isna().sum()

Price                  0
city                   0
Area                   0
Location               0
No. of Bedrooms        0
Resale                 0
MaintenanceStaff       0
Gymnasium              0
SwimmingPool           0
LandscapedGardens      0
JoggingTrack           0
RainWaterHarvesting    0
IndoorGames            0
ShoppingMall           0
Intercom               0
SportsFacility         0
ATM                    0
ClubHouse              0
School                 0
24X7Security           0
PowerBackup            0
CarParking             0
StaffQuarter           0
Cafeteria              0
MultipurposeRoom       0
Hospital               0
WashingMachine         0
Gasconnection          0
AC                     0
Wifi                   0
Children'splayarea     0
LiftAvailable          0
BED                    0
VaastuCompliant        0
Microwave              0
GolfCourse             0
TV                     0
DiningTable            0
Sofa                   0
Wardrobe               0
Stadium                0
dtype: int64

In [28]:
# 2. VARIABLES CATEGORICAS (EXCEPTO TEXTOS O VARIABLES CON MUCHAS CATEGORIAS)
# 2.1. OrdinalEncoding|LabelEncoding (0,1,2, etc..).
#       - Árboles de decisión.
#       - Hay un orden implícito.
# 2.2 OneHotEncoding. Más usada, y recomendada por defecto.
# 2.3 TargetEncoding.

# procesar todas las variables de baja cardinalidad con one hot encoding.

from sklearn.preprocessing import OneHotEncoder

In [29]:
#instanciar el objeto
ohEnconder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [30]:
#extraer datos 

cat_columns = ["city"] + df_w_bool.columns[5:].to_list()
cat_columns

# hacemos fit con datos cat.
ohEnconder.fit(df_w_bool[cat_columns])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [31]:
cat_oh_data = ohEnconder.transform(df_w_bool[cat_columns])

In [32]:
cat_oh_data

array([[0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [33]:
df_cat_oh_data = pd.DataFrame(data=cat_oh_data, columns=ohEnconder.get_feature_names_out(), index=df_train.index)

In [36]:
df_cat_oh_data.head()

,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,Resale_NO,Resale_SI,MaintenanceStaff_NO,MaintenanceStaff_NO_DISPONIBLE,...,DiningTable_SI,Sofa_NO,Sofa_NO_DISPONIBLE,Sofa_SI,Wardrobe_NO,Wardrobe_NO_DISPONIBLE,Wardrobe_SI,Stadium_NO,Stadium_NO_DISPONIBLE,Stadium_SI
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [39]:
df_train['Location'].nunique()

1469

In [40]:
# procesar location.
from skrub import GapEncoder

gapEncoder = GapEncoder(n_components=50)

In [41]:
gapEncoder.fit(df_train['Location'])

GapEncoder(n_components=50)

In [44]:
gapEncoder.get_feature_names_out()

['Location: expressway, extension, delhi',
 'Location: newtown, township, richmond',
 'Location: iyyappanthangal, iyappanthangal, mogappair',
 'Location: nizampet, hafeezpet, kokapet',
 'Location: konnagar, nagar, annanagar',
 'Location: poornapragna, gachibowli, poornaprajna',
 'Location: sholinganallur, nanganallur, navallur',
 'Location: sector12, 112, 108',
 'Location: thiruvanmiyur, prabhadevi, malkajgiri',
 'Location: hennur, nayabad, narayanapura',
 'Location: beyond, road, infantry',
 'Location: dombivali, kandivali, dombivli',
 'Location: madhyamgram, beeramguda, nanakramguda',
 'Location: whitefields, whitefield, junction',
 'Location: kharghar, khar, kaikhali',
 'Location: krishnarajapura, krishna, yeshwantpur',
 'Location: paschim, putiary, hills',
 'Location: santacruz, vasant, punjabi',
 'Location: thane, magathane, west',
 'Location: gajularamaram, kumaraswamy, carmelaram',
 'Location: nalasopara, sopara, kopara',
 'Location: crossing, budigere, railway',
 'Location: nanmangalam, koramangala, nelamangala',
 'Location: noida, bhoiwada, almeida',
 'Location: east, mira, eastend',
 'Location: sector, sector8, sector3',
 'Location: kovilambakkam, perumbakkam, kelambakkam',
 'Location: tollygunge, bunglows, ballygunge',
 'Location: medavakkam, chromepet, mugalivakkam',
 'Location: dwarka, 110075, karkardooma',
 'Location: thiruverkadu, dumdum, kadugodi',
 'Location: bellandur, attibele, selaiyur',
 'Location: banashankari, yelahanka, kailash',
 'Location: uttam, gutta, jeejamata',
 'Location: electronics, electronic, phase',
 'Location: vadapalani, avadi, panchavati',
 'Location: narendrapur, bendre, peenya',
 'Location: andheri, moolacheri, kalyan',
 'Location: ambattur, korattur, chembur',
 'Location: hussainpur, keshtopur, sarjapur',
 'Location: rajarhat, rajarajeshwari, rajeshwari',
 'Location: kolathur, varthur, perungalathur',
 'Location: devanahalli, uttarahalli, bilekahalli',
 'Location: bommasandra, thanisandra, junnasandra',
 'Location: goregaon, alipore, barrackpore',
 'Location: thoraipakkam, karapakkam, kolapakkam',
 'Location: kukatpally, bachupally, kompally',
 'Location: sector24, connector, rohini',
 'Location: chhattarpur, chhatarpur, chattarpur',
 'Location: mukundapur, kondapur, bindapur']

In [45]:
cat_location_data = gapEncoder.transform(df_train['Location'])
cat_location_data

,"Location: expressway, extension, delhi","Location: newtown, township, richmond","Location: iyyappanthangal, iyappanthangal, mogappair","Location: nizampet, hafeezpet, kokapet","Location: konnagar, nagar, annanagar","Location: poornapragna, gachibowli, poornaprajna","Location: sholinganallur, nanganallur, navallur","Location: sector12, 112, 108","Location: thiruvanmiyur, prabhadevi, malkajgiri","Location: hennur, nayabad, narayanapura",...,"Location: rajarhat, rajarajeshwari, rajeshwari","Location: kolathur, varthur, perungalathur","Location: devanahalli, uttarahalli, bilekahalli","Location: bommasandra, thanisandra, junnasandra","Location: goregaon, alipore, barrackpore","Location: thoraipakkam, karapakkam, kolapakkam","Location: kukatpally, bachupally, kompally","Location: sector24, connector, rohini","Location: chhattarpur, chhatarpur, chattarpur","Location: mukundapur, kondapur, bindapur"
0,0.050193,0.052348,0.050000,0.051503,0.054058,0.050658,0.050077,20.707171,0.052585,0.050999,...,0.052621,0.050716,0.050860,0.050394,0.052430,0.055429,0.051201,0.073948,0.051121,0.050000
1,0.050509,0.050000,0.051090,0.051258,0.065622,0.050022,0.052699,0.054959,0.060533,0.053513,...,0.061624,7.278159,0.052521,0.050920,0.050001,0.053689,0.050786,0.050007,0.057265,0.052983
2,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,...,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.051242
3,0.052084,0.050092,0.053586,0.053077,0.050805,0.050008,0.051374,0.050000,0.052088,0.052096,...,0.051496,0.051342,0.051756,0.069684,0.050113,0.050024,0.050378,0.050351,0.050001,0.064896
4,0.064104,0.050013,0.100612,0.050529,7.265003,0.255156,0.056050,0.051375,0.059633,0.187774,...,0.063951,0.051975,0.081313,0.071094,0.071493,0.449267,0.063152,0.051809,0.095224,0.050125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20969,0.052835,0.052153,0.050000,0.050102,0.129004,0.050014,0.050023,1.356379,0.058157,0.483971,...,0.050002,0.082955,0.050323,0.063366,0.050001,0.050003,0.050009,0.070458,0.050001,0.050009
20970,0.068439,0.050000,0.050000,0.050063,0.050000,0.940994,0.050003,0.084541,0.050000,0.050000,...,0.050001,0.050001,0.050000,0.050000,0.262169,0.054317,0.050000,0.082178,0.069173,0.050054
20971,0.050102,0.050144,0.059063,0.052319,0.080628,0.053860,0.067375,0.053369,0.057805,0.062353,...,0.058733,0.052917,0.067355,0.063409,0.050721,0.069093,0.051846,0.050271,0.056324,0.052479
20972,0.050296,0.050000,0.053338,0.050670,0.050000,0.052915,0.072694,0.050000,0.050831,0.068412,...,0.052356,0.053243,0.051171,0.055171,0.050000,0.051875,0.050000,0.064602,0.057313,8.826082
20973,4.415419,0.050001,0.057378,0.050001,0.050000,0.055072,0.050000,0.050000,0.053907,0.050349,...,0.050000,0.050000,0.050306,0.050018,0.050001,0.050002,0.052882,0.059726,0.051127,0.050000

In [47]:
from sklearn.preprocessing import QuantileTransformer

In [98]:
price_Transformer, area_Transformer, beds_Transformer = QuantileTransformer(), QuantileTransformer(), QuantileTransformer()

In [99]:
price_Transformer.fit(df_train[['Price']])
area_Transformer.fit(df_train[['Area']])
beds_Transformer.fit(df_train[['No. of Bedrooms']])

QuantileTransformer()

In [100]:
price_normal = price_Transformer.transform(df_train[['Price']])
area_normal = area_Transformer.transform(df_train[['Area']])
beds_normal = beds_Transformer.transform(df_train[['No. of Bedrooms']])

In [55]:
from sklearn.preprocessing import StandardScaler

In [101]:
scaler_price, scaler_area, scalar_beds = StandardScaler(), StandardScaler(), StandardScaler()

In [102]:
scaler_price.fit(price_normal)
scaler_area.fit(area_normal)
scalar_beds.fit(beds_normal)

price_normal_scaled = scaler_price.transform(price_normal)
area_normal_scaled = scaler_area.transform(area_normal)
beds_normal_scaled = scalar_beds.transform(beds_normal)

In [69]:
area_normal_scaled.flatten()

array([ 0.77282079, -0.55412878, -1.43369157, ...,  0.02456109,
       -1.10763963,  1.5089565 ])

In [104]:
df_normal_scaled = pd.DataFrame(data={'price_normal_scaled':price_normal_scaled.flatten(), 
                                      'area_normal_scaled':area_normal_scaled.flatten(), 
                                      'beds_normal_scaled':beds_normal_scaled.flatten()}, 
                                      index=df_train.index)

In [105]:
df_normal_scaled.head()

   price_normal_scaled  area_normal_scaled  beds_normal_scaled
0             0.778580            0.692592           -0.553803
1            -0.552869            0.987888            0.897291
2            -1.437449           -0.420846            0.897291
3             0.799380           -1.329315           -0.553803
4            -0.509265            0.308708            0.897291

In [106]:
print(df_cat_oh_data.shape)
print(cat_location_data.shape)
print(df_normal_scaled.shape)

(20974, 113)
(20974, 50)
(20974, 3)

In [107]:
# Enriquecer nuestras variables con nuevas features.
# 1.- Añadir features espécificas según negocio.
# 2.- Si tenemos datos temporales, extraer, mes, año, estación, fin de semana, etc..
# 3.- si tuvieramos localización GPS, extraer, ciudad, barrio, etc..
# 4.- Ver interacciones cruzadas.
# 5.- Crear clusters y añadirlos como variables.
# 6.- Crear PCA y añadirlo como variables,
# 7.- etc...

# En este ejemplo de momento solo vamos a añadir interacciones cruzadas.

from sklearn.preprocessing import PolynomialFeatures

In [110]:
polyfeatures = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)

features_to_cross = pd.concat([df_cat_oh_data, df_normal_scaled[['area_normal_scaled', 'beds_normal_scaled']]], axis=1)

In [111]:
features_to_cross.shape

(20974, 115)

In [112]:
polyfeatures.fit(features_to_cross)

PolynomialFeatures(include_bias=False, interaction_only=True)

In [113]:
crossed_features = polyfeatures.transform(features_to_cross)

In [114]:
crossed_features.shape

(20974, 6670)

In [115]:
df_crossed_features = pd.DataFrame(data=crossed_features, columns=polyfeatures.get_feature_names_out(), index=df_train.index)

In [116]:
df_crossed_features

,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,Resale_NO,Resale_SI,MaintenanceStaff_NO,MaintenanceStaff_NO_DISPONIBLE,...,Stadium_NO Stadium_NO_DISPONIBLE,Stadium_NO Stadium_SI,Stadium_NO area_normal_scaled,Stadium_NO beds_normal_scaled,Stadium_NO_DISPONIBLE Stadium_SI,Stadium_NO_DISPONIBLE area_normal_scaled,Stadium_NO_DISPONIBLE beds_normal_scaled,Stadium_SI area_normal_scaled,Stadium_SI beds_normal_scaled,area_normal_scaled beds_normal_scaled
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.000000,-0.000000,0.0,0.000000,-0.000000,0.692592,-0.553803,-0.383560
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.000000,0.000000,0.0,0.987888,0.897291,0.000000,0.000000,0.886424
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,-0.000000,0.000000,0.0,-0.420846,0.897291,-0.000000,0.000000,-0.377622
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,-1.329315,-0.553803,0.0,-0.000000,-0.000000,-0.000000,-0.000000,0.736178
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.308708,0.897291,0.0,0.000000,0.000000,0.000000,0.000000,0.277001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20969,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.000000,-0.000000,0.0,1.161591,-0.553803,0.000000,-0.000000,-0.643292
20970,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.000000,0.000000,0.0,1.656439,1.682779,0.000000,0.000000,2.787420
20971,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.000000,0.000000,0.0,0.551566,0.897291,0.000000,0.000000,0.494915
20972,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,-1.287626,0.897291,0.0,-0.000000,0.000000,-0.000000,0.000000,-1.155376
20973,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,-0.000000,-0.000000,0.0,-0.946009,-0.553803,-0.000000,-0.000000,0.523903

In [119]:
# generar Matriz X y vector y

X_EXPANDED = pd.concat([df_normal_scaled[['area_normal_scaled', 'beds_normal_scaled']],
                        df_cat_oh_data,
                        cat_location_data,
                        df_crossed_features], axis=1)
y = df_normal_scaled['price_normal_scaled']

In [120]:
X_EXPANDED.shape

(20974, 6835)

In [121]:
y.shape

(20974,)

In [123]:
# guardamos los dataframes en modo pickle
DIR = "data/postproccesed/"
df_normal_scaled.to_pickle(DIR + 'df_normal_scaled.pkl')
df_cat_oh_data.to_pickle(DIR + 'df_cat_oh_data.pkl')
cat_location_data.to_pickle(DIR + 'cat_location_data.pkl')
df_crossed_features.to_pickle(DIR + 'df_crossed_features.pkl')
# guardamos también X e Y
X_EXPANDED.to_pickle(DIR +'X_EXPANDED.pkl')
y.to_pickle(DIR +'y.pkl')

In [128]:
# guardar objeto sklearn
import pickle
def save_proccesed_fea(name, object):
    with open('data/postproccesed/preproccesing_' + name + '.pkl', 'wb') as f:
        pickle.dump(object, f)

In [129]:
save_proccesed_fea('beds_imputer',imputer)

In [131]:
save_proccesed_fea('ohEncoder',ohEnconder)

In [133]:
save_proccesed_fea('gapEncoder',gapEncoder)