In [2]:
#Importamos las librerias necesarias

import pandas as pd
import os

In [3]:
# Configurar el directorio donde se encuentran los archivos CSV
data_path = "../data/source"

# Leer todos los archivos CSV en la carpeta
all_files = [os.path.join(data_path, f) for f in os.listdir(data_path) if f.endswith('.csv')]

all_files

['../data/source/Hyderabad.csv',
 '../data/source/Delhi.csv',
 '../data/source/Kolkata.csv',
 '../data/source/Chennai.csv',
 '../data/source/Mumbai.csv',
 '../data/source/Bangalore.csv']

In [4]:
# Lista para almacenar los DataFrames
dfs = []

# Leer cada archivo CSV y almacenarlo en la lista
for file in all_files:
    # leemos del archivo csv
    df = pd.read_csv(file)
    # añadimos una columna con el nombre de la ciudad al principio.
    df.insert(1,'city',file.split('/')[-1].split('.csv')[0])
    # añadimos el dataframe a la lista
    dfs.append(df)

# visualizamos el tamaño de cada dataframe
[df.shape for df in dfs]

[(2018, 41), (4498, 41), (6007, 41), (4514, 41), (7219, 41), (5707, 41)]

In [5]:
# Concatenar todos los DataFrames en uno solo
combined_df = pd.concat(dfs, ignore_index=True)

In [6]:
# visualizamos las primeras columnas
combined_df.head()

,Price,city,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
0,6968000,Hyderabad,1340,Nizampet,2,0,0,1,1,1,...,1,0,1,0,0,0,0,0,0,0
1,29000000,Hyderabad,3498,Hitech City,4,0,0,1,1,1,...,1,0,1,0,0,0,0,0,0,0
2,6590000,Hyderabad,1318,Manikonda,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5739000,Hyderabad,1295,Alwal,3,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,5679000,Hyderabad,1145,Kukatpally,2,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0

In [7]:
# visualizamos el tamaño
combined_df.shape

(29963, 41)

In [8]:
# barajamos para que estén desordenadaso
combined_df = combined_df.sample(frac=1)
combined_df.head()

,Price,city,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,...,LiftAvailable,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Stadium
27555,5588000,Bangalore,2350,ITPL,3,0,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
8277,5900000,Kolkata,734,Rajarhat,2,0,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
2207,18000000,Delhi,1900,Sector 13 Dwarka,4,1,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0
15390,4659000,Chennai,1702,Thalambur,3,0,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
26292,5964000,Bangalore,1205,Varthur,2,0,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [11]:

# Save the dataframe to a CSV file
preprocessed_path = "../data/preprocessed"
combined_df.to_csv(os.path.join(preprocessed_path, "combined_data.csv"), index=False)

In [12]:
from sklearn.model_selection import train_test_split

# Split the data into train and test sets
train_df, test_df = train_test_split(combined_df, test_size=0.3, random_state=42)

# Display the shapes of the train and test sets
print("Train set shape:", train_df.shape)
print("Test set shape:", test_df.shape)

Train set shape: (20974, 41)
Test set shape: (8989, 41)

In [14]:
# Save the train and test dataframes to CSV files
train_df.to_csv(os.path.join(preprocessed_path, "train_data.csv"), index=False)
test_df.to_csv(os.path.join(preprocessed_path, "test_data.csv"), index=False)